from __future__ import annotations

import json
from pathlib import Path


def generate_opencode_adapter(
    tldr_path: str | list[str],
    *,
    enable_tool_guard: bool = False,
    enable_compact_context: bool = False,
) -> str:
    if isinstance(tldr_path, list):
        resolved_parts = []
        for part in tldr_path:
            p = Path(part)
            if p.exists() or p.is_absolute():
                resolved_parts.append(str(p.expanduser().resolve()))
            else:
                resolved_parts.append(part)
        tldr_command_json = json.dumps(resolved_parts)
    else:
        abs_tldr_path = str(Path(tldr_path).expanduser().resolve())
        tldr_command_json = json.dumps([abs_tldr_path])

    # Optional callbacks. These are not part of the default install because
    # OpenCode's plugin surface is callback-based and not every callback can
    # safely alter execution. Keep them opt-in until fixture-tested locally.
    opt_callbacks_js = ""
    if enable_tool_guard:
        opt_callbacks_js += """*,
        "permission.asked": async (input = {}, output = {}) => {
            const payload = buildToolPayload("permission-request", input, output, contextData);
            const parsed = await runTldrJson("permission-request", payload);
            applyBlockingDecision(parsed);
            return {};
        }"""

    if enable_compact_context:
        opt_callbacks_js += """*,
        "experimental.session.compacting": async (input = {}, output = {}) => {
            const payload = {
                hook_event_name: "pre-compact",
                cwd: cwd,
                session_id: sessionId,
                raw: { input, output: summarizeOutput(output), context: contextSummary }
            };
            const parsed = await runTldrJson("pre-compact", payload);
            appendAdditionalContext(parsed, output);
            return {};
        }"""

    # Replace placeholder stars with actual commas so formatting remains clean
    opt_callbacks_js = opt_callbacks_js.replace("*,", ",")

    return f"""// tldr-hooks.js - Generated by TLDR Hooks Installer
import {{ spawn }} from "node:child_process";

const TLDR_COMMAND = {tldr_command_json};
const TLDR_TIMEOUT_MS = 1500;

function resolveCwd(context) {{
    if (typeof context?.directory === "string" && context.directory.length > 0) {{
        return context.directory;
    }}
    if (typeof context?.worktree === "string" && context.worktree.length > 0) {{
        return context.worktree;
    }}
    if (typeof context?.project?.directory === "string" && context.project.directory.length > 0) {{
        return context.project.directory;
    }}
    if (typeof context?.project?.path === "string" && context.project.path.length > 0) {{
        return context.project.path;
    }}
    if (typeof context?.project?.root === "string" && context.project.root.length > 0) {{
        return context.project.root;
    }}
    return process.cwd();
}}

function summarizeContext(context) {{
    return {{
        directory: typeof context?.directory === "string" ? context.directory : undefined,
        worktree: typeof context?.worktree === "string" ? context.worktree : undefined,
        project: {{
            id: context?.project?.id,
            name: context?.project?.name,
            directory: context?.project?.directory,
            path: context?.project?.path,
            root: context?.project?.root,
        }},
    }};
}}

function summarizeOutput(output) {{
    return {{
        args: output?.args,
        contextLength: Array.isArray(output?.context) ? output.context.length : undefined,
        hasPrompt: typeof output?.prompt === "string",
    }};
}}

function hookSpecific(parsed) {{
    return parsed?.hookSpecificOutput || {{}};
}}

function additionalContext(parsed) {{
    return hookSpecific(parsed).additionalContext || parsed?.additionalContext || parsed?.message;
}}

function decisionReason(parsed) {{
    return (
        parsed?.reason ||
        hookSpecific(parsed).permissionDecisionReason ||
        hookSpecific(parsed).decision?.message ||
        "Blocked by TLDR"
    );
}}

function shouldBlock(parsed) {{
    const specific = hookSpecific(parsed);
    return (
        parsed?.decision === "block" ||
        specific.permissionDecision === "deny" ||
        specific.decision?.behavior === "deny"
    );
}}

function applyBlockingDecision(parsed) {{
    if (shouldBlock(parsed)) {{
        throw new Error(decisionReason(parsed));
    }}
}}

function applyUpdatedInput(parsed, output) {{
    const updatedInput = hookSpecific(parsed).updatedInput || parsed?.updatedInput;
    if (!updatedInput || typeof updatedInput !== "object") {{
        return;
    }}
    output.args = {{ ...(output.args || {{}}), ...updatedInput }};
}}

function appendAdditionalContext(parsed, output) {{
    const context = additionalContext(parsed);
    if (!context) {{
        return;
    }}
    if (Array.isArray(output?.context)) {{
        output.context.push(String(context));
    }}
}}

function safeStringify(obj) {{
    const seen = new WeakSet();
    return JSON.stringify(obj, (key, value) => {{
        if (typeof value === "object" && value !== null) {{
            if (seen.has(value)) {{
                return "[Circular]";
            }}
            seen.add(value);
        }}
        return value;
    }});
}}

function runTldr(event, payload) {{
    return new Promise((resolve, reject) => {{
        let resolved = false;
        const child = spawn(TLDR_COMMAND[0], [...TLDR_COMMAND.slice(1), "hooks", "run", event, "--client", "opencode"]);
        child.stdin.on("error", () => {{}});
        
        let stdout = "";
        let stderr = "";
        
        const timer = setTimeout(() => {{
            if (!resolved) {{
                resolved = true;
                try {{
                    child.kill("SIGKILL");
                }} catch (e) {{}}
                reject(new Error(`Timeout after ${{TLDR_TIMEOUT_MS}}ms`));
            }}
        }}, TLDR_TIMEOUT_MS);
        
        child.stdout.on("data", (data) => {{
            stdout += data.toString();
        }});
        
        child.stderr.on("data", (data) => {{
            stderr += data.toString();
        }});
        
        child.on("error", (err) => {{
            if (!resolved) {{
                resolved = true;
                clearTimeout(timer);
                reject(err);
            }}
        }});
        
        child.on("close", (code) => {{
            if (!resolved) {{
                resolved = true;
                clearTimeout(timer);
                if (code !== 0) {{
                    reject(new Error(`Subprocess exited with code ${{code}}: ${{stderr}}`));
                }} else {{
                    resolve(stdout);
                }}
            }}
        }});
        
        try {{
            child.stdin.write(safeStringify(payload));
        }} catch (e) {{
            // ignore
        }}
        child.stdin.end();
    }});
}}

async function runTldrJson(event, payload) {{
    try {{
        const stdout = await runTldr(event, payload);
        if (!stdout || stdout.trim() === "") {{
            return {{}};
        }}
        return JSON.parse(stdout);
    }} catch (err) {{
        console.error(`[TLDR Hooks] ${{event}} no-op: ${{err.message}}`);
        return {{}};
    }}
}}

function toolNameFrom(input = {{}}) {{
    return input.tool || input.toolName || input.tool_name || input.name;
}}

function toolInputFrom(input = {{}}, output = {{}}) {{
    return output.args || input.args || input.toolInput || input.tool_input || input.input || {{}};
}}

function buildToolPayload(event, input = {{}}, output = {{}}, contextData = {{}}) {{
    const toolName = toolNameFrom(input);
    const toolInput = toolInputFrom(input, output);
    return {{
        hook_event_name: event,
        cwd: contextData.cwd,
        session_id: contextData.sessionId,
        tool_name: toolName,
        tool_input: toolInput,
        raw: {{ input, output: summarizeOutput(output), context: contextData.contextSummary }}
    }};
}}

export const TLDRHooks = async (context) => {{
    const cwd = resolveCwd(context);
    const sessionId = context?.client?.sessionId || context?.client?.id || context?.project?.id;
    const contextSummary = summarizeContext(context);
    const contextData = {{ cwd, sessionId, contextSummary }};

    const hooks = {{
        "session.created": async (input = {{}}, output = {{}}) => {{
            const payload = {{
                hook_event_name: "session-start",
                cwd: cwd,
                session_id: sessionId,
                raw: {{ input, output: summarizeOutput(output), context: contextSummary }}
            }};
            const parsed = await runTldrJson("session-start", payload);
            appendAdditionalContext(parsed, output);
            return {{}};
        }},

        "tool.execute.before": async (input = {{}}, output = {{}}) => {{
            const toolName = toolNameFrom(input);
            const toolLower = (toolName || "").toLowerCase();
            let event = "pre-tool";
            if (["read", "glob", "grep"].includes(toolLower)) {{
                event = "pre-read";
            }} else if (["edit", "write", "multiedit", "update", "create", "applypatch"].includes(toolLower)) {{
                event = "pre-edit";
            }}

            const payload = buildToolPayload(event, input, output, contextData);
            const parsed = await runTldrJson(event, payload);
            applyBlockingDecision(parsed);
            applyUpdatedInput(parsed, output);
            appendAdditionalContext(parsed, output);
            return {{}};
        }},

        "tool.execute.after": async (input = {{}}, output = {{}}) => {{
            const toolName = toolNameFrom(input);
            const toolLower = (toolName || "").toLowerCase();
            const isEdit = ["edit", "write", "multiedit", "update", "create", "applypatch"].includes(toolLower);
            if (!isEdit) {{
                return {{}};
            }}

            const payload = {{
                hook_event_name: "post-edit",
                cwd: cwd,
                session_id: sessionId,
                tool_name: toolName,
                tool_input: toolInputFrom(input, output),
                tool_result: output.result || output.response || input.result || input.response || {{}},
                raw: {{ input, output: summarizeOutput(output), context: contextSummary }}
            }};
            const parsed = await runTldrJson("post-edit", payload);
            appendAdditionalContext(parsed, output);
            return {{}};
        }},

        "file.edited": async (input = {{}}, output = {{}}) => {{
            const filePath = input.filePath || input.file_path || input.path || input.file?.path;
            const payload = {{
                hook_event_name: "post-edit",
                cwd: cwd,
                session_id: sessionId,
                tool_name: "Edit",
                tool_input: {{ file_path: filePath }},
                raw: {{ input, output: summarizeOutput(output), context: contextSummary }}
            }};
            const parsed = await runTldrJson("post-edit", payload);
            appendAdditionalContext(parsed, output);
            return {{}};
        }}{opt_callbacks_js}
    }};

    return hooks;
}};

export default TLDRHooks;
"""
